### ISSUE TITLE
Document config files better

### ISSUE THREAD

**Issue by nkrusch** [MobileFirstLLC/extension-cli#24]
**Describe the issue**

There are multiple [config files](https://github.com/MobileFirstLLC/extension-cli/tree/master/config) (excluding `init/`) with file ending `.js` meaning they are executable code and can cause failures at runtime.

These need to be better documented and ideally verified.

**Goal**

Minimize chance of error in these files

**Tasks**

- [x] update `createPrompts.js`
- [x] update `rootSuite.js`
- [x] update `texts.js` 
- [x] add `config/README.md` w/ short description of each file
