### ISSUE TITLE
Complexity and tech debt considerations

### ISSUE THREAD

**Issue by nkrusch** [MobileFirstLLC/extension-cli#73]
After [moving all code files](https://github.com/MobileFirstLLC/extension-cli/pull/67) to cli the [maintainability decreased](https://codeclimate.com/github/MobileFirstLLC/extension-cli). The task is to address these complexity issues or mark them as wontfix.

**Tasks**

Code smells

Fixing this [one function](https://codeclimate.com/github/MobileFirstLLC/extension-cli/cli/rootsuite.js/source#issue-8c870c1fec3458a5b0a99595d9b03452) would take care of most smell issues:

- [ ] mouseEvent has 35 lines of code
- [ ] mouseEvent has a Cognitive Complexity of 8
- [ ] mouseEvent has 5 arguments
- [ ] [keyReplace has a Cognitive Complexity of 10](https://codeclimate.com/github/MobileFirstLLC/extension-cli/cli/utilities.js/source#issue-3cd00279a16470a62c447405dd9dcdf4)
- [ ] [iterateConfigs has a Cognitive Complexity of 10](https://codeclimate.com/github/MobileFirstLLC/extension-cli/cli/utilities.js/source#issue-58395011255e79a4618df5173bec7c2a)
- ignore: [Consider simplifying this complex logical expression](https://codeclimate.com/github/MobileFirstLLC/extension-cli/cli/xt-clean.js/source#issue-9b96275357497ab09f0034c87ecd97b4) &rarr; likely fix by #25

Duplication

- [ ] [Similar blocks of code...](https://codeclimate.com/github/MobileFirstLLC/extension-cli/cli/gulpfile.js/source#issue-e07a3a5e2a1c5063b6b84d6b3b7df2df)
- ignore: [Similar blocks of code...](https://codeclimate.com/github/MobileFirstLLC/extension-cli/cli/xt-clean.js/source#issue-6bd43a64e1678b2360387112107aa8bf) &rarr; likely fix by #25
